### ISSUE TITLE
Users should be able to change their password in the profile screen.

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#171]

**Comment by tasermonkey** [comment]
Do you want the user to have to press a separate button for "save password" or do you want it to be set if its filled out when they click "save changes"?  E.g. should I make a new endpoint or make it so that the save_profile endpoint sees if "old_password" is there, followed by: "new_password" is set.

**Comment by walkeriniraq** [comment]
Meh - not really worried about it. It's an important feature, but not one
that will get used that much. Whatever's easiest, I say.

**Comment by walkeriniraq** [comment]
This is working.
