### ISSUE TITLE
GET /api/v2/stream?start=XXXX always returns nothing

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#202]
to reproduce:

1. run `curl -L -o - https://jccc5.rylath.net/api/v2/stream` and note the next_page entry
2. run `curl -L -o - https://jccc5.rylath.net/api/v2/stream?start=...` using the next_page entry

When making a request using `?start=` it has no "Content-Length" header and returns no data.

```
$ curl --verbose --insecure -L -o - https://jccc5.rylath.net/api/v2/stream'?start=1421003782001' 
* Hostname was NOT found in DNS cache
*   Trying 65.78.173.20...
* Connected to jccc5.rylath.net (65.78.173.20) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: jccc5.rylath.net
> GET /api/v2/stream?start=1421003782001 HTTP/1.1
> User-Agent: curl/7.37.1
> Host: jccc5.rylath.net
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server nginx/1.1.19 is not blacklisted
< Server: nginx/1.1.19
< Date: Sun, 11 Jan 2015 19:28:42 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< ETag: "3c2ecaa0334b4f330c8d739524007e6c"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: 94c7d5fe-af80-419f-88fa-768a590d0ce7
< X-Runtime: 0.014000
< Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin, Referer, User-Agent, X-Requested-With
< 
* Connection #0 to host jccc5.rylath.net left intact
```

**Comment by walkeriniraq** [comment]
I'll let @james take this one.  :)

**Comment by tasermonkey** [comment]
that is because there is no new posts.... By default it means, "Posts newer than" ....
If you want "older than" you will need to do:
https://jccc5.rylath.net/api/v2/stream?start=1421028058001&older_posts=true
(though the "next_page" thing would be a timestamp that is 1 unit after the newest post, if you didn't put down "older_posts" to begin with)  Though older_posts=true also works without a "start" which will default to now.

The idea is, that you can know when you want to refresh (automatically or what not), where to tell it to find the posts that the user already seen -vs- new one posted.
