### ISSUE TITLE
Client side image resizing

### ISSUE THREAD

**Issue by Wingar** [walkeriniraq/twitarr#216]
So, lets be honest the existing scaling is... Not so pretty. It works but there's no filtering, and I've looked very hard and there's just no way to do it with the lib, so why not client side scaling at upload, iirc ember has helpers for it,just fall back on server side scaling if there's some issue.

Thoughts? Is this even practical (performance)?

**Comment by tasermonkey** [comment]
@Wingar is there another java library that can?  We could write a simple wrapper does it. Or even another ruby one.

**Comment by Wingar** [comment]
Considered it, but one issue is they all seem to have C dependencies, and with JRuby..., also it seems like it might be a bit close to change and fully test a new lib

**Comment by walkeriniraq** [comment]
I've tried every Image processing library I could find - most of them suck.

This one gives me hope, but the last build doesn't have the features we need, and I didn't want to switch this close to "deployment".  https://github.com/jruby/image_voodoo

**Comment by walkeriniraq** [comment]
@Wingar and I just came up with an idea. She suggested the nginx module http://nginx.org/en/docs/http/ngx_http_image_filter_module.html for resizing images. Unfortunately it doesn't handle exif correctly. 

So we'll use both. We'll use the java library to deal with the exif and prune them down to a smaller size, then use the nginx module to bring them to the correct size for the page.

I only need to set it up for the small images and the small profile images - since we have so many of those I want to make sure that they're exactly the size the browser's expecting for best performance. The larger images are generally only viewed one-at-a-time, so there's no reason to resize them.

**Comment by tasermonkey** [comment]
Still sounds painful, but I'm not going to argue with this, as I have no
better suggestion,.

- James
jstaplet@jamesstapleton.com
https://keybase.io/jstapleton

**Comment by walkeriniraq** [comment]
Pfft. That's never stored me from arguing.

**Comment by walkeriniraq** [comment]
The big concern I have now is whether the nginx version I've installed from the ubuntu repo has this module installed.

I don't really have time to fiddle with it right now, so I'll try later. Worst case if I don't get around to it is that Twitarr is slightly slower since users will be loading larger images and the browser will have to resize them itself.

**Comment by Wingar** [comment]
It probably doesn't, but `Nginx -V` will tell you.
I suggest using the settings that it gives you and recompiling it, it's like Nginx 1.1.9 or something right now, isn't it?

**Comment by tasermonkey** [comment]
Yeah, the response headers from jccc5.rylath.net is `Server:nginx/1.1.19`

Isn't it just easy enough to use the ppa from http://wiki.nginx.org/Install ?

**Comment by Wingar** [comment]
The module isn't enabled by default, so I don't imagine it would be enabled in the package.

**Comment by walkeriniraq** [comment]
I think we fixed this?
