### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#259]
We will need a read-only mode.

**Comment by Wingar** [comment]
Should probably revert the branch to the version we were using on the boat. Commit e52ce7b was the last before we sailed.

**Comment by tasermonkey** [comment]
Alright, though I only did this because it was a thought in the back of my head as well, and you mentioned it out loud.  The reason why I didn't branch from the time in the past was because every change was backwards compatible with the database anyways.   


Tagged JCCC5 at change #e52ce7b6016c71a54b517e281672666400e04488
And then created 2 new branches: JCCC5 to be any changes for JCCC5 
Then my feature branch: jccc5-read-only-mode because its still incomplete.

We can then merge jccc5-read-only-mode  into both master and JCCC5 when the front end issues are worked out.

**Comment by Wingar** [comment]
The forum pagination isn't backwards compatible. It requires some small work to set last_post_time else it'll sort the forums wrong.

**Comment by tasermonkey** [comment]
ah!  Alright, fair enough. Laziness still wins as no point in making anything that would go back and update any existing data. :-)

**Comment by walkeriniraq** [comment]
I want to make it so that the profiles aren't visible unless you're logged in, and that nobody can create an account. That should help keep personal info off the internet at large. I'd also like people to be able to edit their profile if they want - I know I'm paranoid, but...

Have you guys been working on the Ruby side? Cause I'd sure appreciate it - I've been too sick to do any work on this.  :(

**Comment by tasermonkey** [comment]
I got the readonly part down on the ruby side.  On the branch jccc5-read-only-mode.  Basically used the config flag "readonly" and only allowed admins to by-pass it.

But it make sense to me about the profiles... I debated on even enforcing not viewing anything while not logged in.

**Comment by Grimoire42** [comment]
I know in the past, some people had requested that the Twit-arr archive be
only visible on the Internet if you were logged in.  Not just profiles, but
the actual twarts (oh how I love that word).  I think that should apply to
forum posts too.  The reasoning behind it was that they didn't consider
Twit-arr to be the "real Internet" when composing their messages, and as
such didn't necessarily self censor to the same extent.

I think it reasonable to restrict any message viewing to logged in users
only.  Might get some push back from users who have since forgotten their
passwords, so perhaps leave the forgotten password reset feature enabled.
How technically feasible that is, I don't know.  :)

Grimoire aka David Rowley

**Comment by Wingar** [comment]
Yeah, I'm all for non-public everything, especially with that reasoning.

**Comment by walkeriniraq** [comment]
Sounds good to me.

**Comment by Wingar** [comment]
Do we have the final database/photo-store from Glenn yet? We should probably get this up fairly soon.

**Comment by walkeriniraq** [comment]
Closing since this was either done or completely unimportant at this point.
