### ISSUE TITLE
unable to update user in cruisemonkey

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#283]
I'm unable to add a "display name" to the default `admin` user in CruiseMonkey.  When I do, I get the following in the twitarr logs:

```
Started POST "/api/v2/user/profile" for 127.0.0.1 at 2017-01-25 09:43:57 -0500
Processing by API::V2::UserController#update_profile as JSON
  Parameters: {"room_number"=>nil, "real_name"=>nil, "unnoticed_alerts"=>false, "current_location"=>nil, "empty_password?"=>"[FILTERED]", "last_login"=>"2017-01-24T22:10:33.911+00:00", "last_photo_updated"=>1485290317, "key"=>"admin:XXXX", "email_public?"=>nil, "display_name"=>"I have a long display name!", "username"=>"admin", "vcard_public?"=>true, "is_admin"=>true, "email"=>"admin@james.com", "status"=>"active", "home_location"=>nil, "user"=>{}}
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 1.0000ms
  MOPED: 127.0.0.1:27017 QUERY        database=twitarr collection=users selector={"$query"=>{"un"=>"admin"}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 1.0000ms
Completed 422 Unprocessable Entity in 46ms (Views: 39.7ms)
```

Not sure how to tell why/how it is unprocessable.  Any ideas?

**Comment by walkeriniraq** [comment]
Huh. Can you try this against the server and see if it has the same issue?

**Comment by walkeriniraq** [comment]
Wait - why do we have two different format timestamps? There's one type for "last login" and one type for "last photo updated"?

**Comment by RangerRick** [comment]
Don't look at me, I voted for Kodos.

**Comment by walkeriniraq** [comment]
Those are the post parameters, which are sent by CM, correct?... But dates are not the problem anyway.

https://github.com/walkeriniraq/twitarr/blob/master/app/controllers/api/v2/user_controller.rb#L38

That's the controller. It returns "unprocessable entity" if it can't save the user object, which it would do if any of the validations fail. I suspect that since you're not getting a 200 the response body is being ignored by your framework, which makes sense - I would ignore the body as well if I were writing a framework.

Status codes should be browser-level messages, not app-level messages. So that should be returning 200, not 422.

I'm 99% sure it's failing because you're passing nil for the location. Just don't send a location, then it should work.

I'll change the status code to 200 when I get a chance so that you'd actually be able to see the output of the validations.

**Comment by RangerRick** [comment]
OK.  Weird that it's validating that nil is wrong for location, when that's what I'm getting *from* twitarr in the first place (I'm grabbing the structure I get back from ReST, changing it, and sending it back).

**Comment by walkeriniraq** [comment]
Yeah, that's wrong. Not sure what's going on there, location was added last
year when I wasn't working on it.

**Comment by walkeriniraq** [comment]
@RangerRick let me know if this works for you and I'll close this ticket.

FYI much of the API returns these http status codes, and I'm not going to go through fixing all of them at this time, so if you run into more problems just let me know which ones need fixing and I'll fix them.

**Comment by walkeriniraq** [comment]
Fixed
